apiVersion: v1
kind: Pod
metadata: 
  name: igress-app
  labels: 
    app: cloth-app
spec:
  containers:
    - image:  nginx
      name:  my-name
      ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: cloth-service-service
spec:
  selector:
    app: cloth-app
  ports:
   - port: 80
     targetPort: 80
  type: NodePort
